veonik_manage:
    resource: "@VeonikBlogBundle/Controller/Admin/"
    type:     annotation
    prefix:   /

veonik_search:
    resource: "@VeonikBlogBundle/Controller/SearchController.php"
    type:     annotation
    prefix:   /

veonik_comment:
    resource: "@VeonikBlogBundle/Controller/CommentController.php"
    type:     annotation
    prefix:   /

veonik_home:
    resource: "@VeonikBlogBundle/Controller/HomeController.php"
    type:     annotation
    prefix:   /
